<?php

declare(strict_types=1);

namespace Netresearch\NrLandingpage\EventListener;

use Doctrine\DBAL\ParameterType;
use Netresearch\NrLandingpage\Service\TemplateService;
use TYPO3\CMS\Backend\Controller\Event\ModifyPageLayoutContentEvent;
use TYPO3\CMS\Backend\Routing\UriBuilder;
use TYPO3\CMS\Core\Attribute\AsEventListener;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Localization\LanguageService;

/**
 * Displays an info callout in the Page module for pages generated by the
 * Landing Page Wizard, showing template name, generation date, briefing
 * answers, and a warning when the template configuration has changed.
 */
#[AsEventListener]
final class AddGenerationInfoListener
{
    public function __construct(
        private readonly ConnectionPool $connectionPool,
        private readonly TemplateService $templateService,
        private readonly UriBuilder $uriBuilder,
    ) {}

    public function __invoke(ModifyPageLayoutContentEvent $event): void
    {
        $request = $event->getRequest();
        $rawPageId = $request->getQueryParams()['id'] ?? 0;
        $pageId = is_numeric($rawPageId) ? (int) $rawPageId : 0;

        if ($pageId <= 0) {
            return;
        }

        $metadata = $this->loadGenerationMetadata($pageId);
        if ($metadata === null) {
            return;
        }

        $rawTemplateUid = $metadata['tx_nrlandingpage_template_uid'] ?? 0;
        $templateUid = is_numeric($rawTemplateUid) ? (int) $rawTemplateUid : 0;
        if ($templateUid <= 0) {
            return;
        }

        $html = $this->renderInfoBox($metadata, $templateUid, $pageId);
        $event->addHeaderContent($html);
    }

    /**
     * @return array<string, mixed>|null
     */
    private function loadGenerationMetadata(int $pageUid): ?array
    {
        $queryBuilder = $this->connectionPool->getQueryBuilderForTable('pages');
        $queryBuilder->getRestrictions()->removeByType(
            \TYPO3\CMS\Core\Database\Query\Restriction\HiddenRestriction::class,
        );
        $row = $queryBuilder
            ->select(
                'tx_nrlandingpage_template_uid',
                'tx_nrlandingpage_briefing_data',
                'tx_nrlandingpage_config_hash',
                'tx_nrlandingpage_generated_at',
                'tx_nrlandingpage_source_page_uid',
            )
            ->from('pages')
            ->where(
                $queryBuilder->expr()->eq('uid', $queryBuilder->createNamedParameter($pageUid, ParameterType::INTEGER)),
            )
            ->executeQuery()
            ->fetchAssociative();

        if ($row === false) {
            return null;
        }

        $templateUid = is_numeric($row['tx_nrlandingpage_template_uid'] ?? null)
            ? (int) $row['tx_nrlandingpage_template_uid']
            : 0;

        return $templateUid > 0 ? $row : null;
    }

    /**
     * @param array<string, mixed> $metadata
     */
    private function renderInfoBox(array $metadata, int $templateUid, int $pageId): string
    {
        $lang = $this->getLanguageService();
        $template = $this->templateService->loadByUid($templateUid);

        if ($template !== null) {
            $templateName = htmlspecialchars($template->title, ENT_QUOTES, 'UTF-8');
        } else {
            $label = $lang->sL('LLL:EXT:nr_landingpage/Resources/Private/Language/locallang.xlf:generationInfo.templateDeleted');
            $templateName = $label !== '' ? $label : 'Template deleted';
        }

        $generatedAt = is_numeric($metadata['tx_nrlandingpage_generated_at'] ?? null)
            ? (int) $metadata['tx_nrlandingpage_generated_at']
            : 0;
        $generatedAtFormatted = $generatedAt > 0
            ? htmlspecialchars(date('Y-m-d H:i', $generatedAt), ENT_QUOTES, 'UTF-8')
            : '–';

        $sourcePageUid = is_numeric($metadata['tx_nrlandingpage_source_page_uid'] ?? null)
            ? (int) $metadata['tx_nrlandingpage_source_page_uid']
            : 0;

        // Check config hash divergence
        $storedHash = is_string($metadata['tx_nrlandingpage_config_hash'] ?? null)
            ? $metadata['tx_nrlandingpage_config_hash']
            : '';
        $configChanged = false;
        if ($template !== null && $storedHash !== '') {
            $configChanged = $template->getConfigHash() !== $storedHash;
        }

        // Parse briefing answers
        $briefingRaw = is_string($metadata['tx_nrlandingpage_briefing_data'] ?? null)
            ? $metadata['tx_nrlandingpage_briefing_data']
            : '';
        $briefingAnswers = [];
        if ($briefingRaw !== '') {
            $decoded = json_decode($briefingRaw, true);
            if (is_array($decoded)) {
                $briefingAnswers = $decoded;
            }
        }

        $title = $lang->sL('LLL:EXT:nr_landingpage/Resources/Private/Language/locallang.xlf:generationInfo.title');
        $titleText = $title !== '' ? $title : 'AI-Generated Landing Page';

        // Metadata line: template + date as readable inline text
        $templateLabel = $lang->sL('LLL:EXT:nr_landingpage/Resources/Private/Language/locallang.xlf:generationInfo.template');
        $dateLabel = $lang->sL('LLL:EXT:nr_landingpage/Resources/Private/Language/locallang.xlf:generationInfo.generatedAt');
        $metaLine = '<strong>' . htmlspecialchars($templateLabel !== '' ? $templateLabel : 'Template', ENT_QUOTES, 'UTF-8')
            . ':</strong> ' . $templateName
            . ' &nbsp;&middot;&nbsp; '
            . '<strong>' . htmlspecialchars($dateLabel !== '' ? $dateLabel : 'Generated', ENT_QUOTES, 'UTF-8')
            . ':</strong> ' . $generatedAtFormatted;

        if ($sourcePageUid > 0) {
            $regenLabel = $lang->sL('LLL:EXT:nr_landingpage/Resources/Private/Language/locallang.xlf:generationInfo.sourcePageUid');
            $metaLine .= ' &nbsp;&middot;&nbsp; '
                . '<strong>' . htmlspecialchars($regenLabel !== '' ? $regenLabel : 'Re-generated from page', ENT_QUOTES, 'UTF-8')
                . ':</strong> #' . $sourcePageUid;
        }

        // Briefing details as collapsible section
        $briefingHtml = '';
        if ($briefingAnswers !== []) {
            $briefingLabel = $lang->sL('LLL:EXT:nr_landingpage/Resources/Private/Language/locallang.xlf:generationInfo.briefing');

            $answerRows = '';
            foreach ($briefingAnswers as $question => $answer) {
                $questionStr = (string) $question;
                $answerStr = is_string($answer) ? $answer : (is_scalar($answer) ? (string) $answer : '');
                $answerRows .= '<tr>'
                    . '<td class="text-nowrap pe-3" style="width:1%"><strong>'
                    . htmlspecialchars($questionStr, ENT_QUOTES, 'UTF-8') . '</strong></td>'
                    . '<td>' . htmlspecialchars($answerStr, ENT_QUOTES, 'UTF-8') . '</td>'
                    . '</tr>';
            }
            $briefingHtml = '<details class="mt-2">'
                . '<summary style="cursor:pointer">'
                . htmlspecialchars($briefingLabel !== '' ? $briefingLabel : 'Briefing', ENT_QUOTES, 'UTF-8')
                . '</summary>'
                . '<table class="table table-sm table-borderless mb-0 mt-1"><tbody>'
                . $answerRows
                . '</tbody></table>'
                . '</details>';
        }

        // Config changed warning
        $warningHtml = '';
        if ($configChanged) {
            $warningMsg = $lang->sL('LLL:EXT:nr_landingpage/Resources/Private/Language/locallang.xlf:generationInfo.configChanged');
            if ($warningMsg === '') {
                $warningMsg = 'The template configuration has changed since this page was generated. Consider re-generating.';
            }
            $warningHtml = '<div class="alert alert-warning mt-2 mb-0 py-1 px-2 small">'
                . htmlspecialchars($warningMsg, ENT_QUOTES, 'UTF-8')
                . '</div>';
        }

        // Re-generate button
        $regenerateUrl = (string) $this->uriBuilder->buildUriFromRoute('nr_landingpage', [
            'regeneratePageUid' => $pageId,
            'autoStartWizard' => 1,
        ]);
        $regenerateLabel = $lang->sL('LLL:EXT:nr_landingpage/Resources/Private/Language/locallang.xlf:contextMenu.regenerateLandingPage');
        if ($regenerateLabel === '') {
            $regenerateLabel = 'Re-Generate Landing Page';
        }

        return '<div class="callout callout-info callout-sm">'
            . '<div class="callout-content">'
            . '<div class="callout-title d-flex justify-content-between align-items-center">'
            . htmlspecialchars($titleText, ENT_QUOTES, 'UTF-8')
            . '<a href="' . htmlspecialchars($regenerateUrl, ENT_QUOTES, 'UTF-8')
            . '" class="btn btn-default btn-sm">'
            . htmlspecialchars($regenerateLabel, ENT_QUOTES, 'UTF-8') . '</a>'
            . '</div>'
            . '<div class="callout-body">'
            . $metaLine
            . $briefingHtml
            . $warningHtml
            . '</div>'
            . '</div>'
            . '</div>';
    }

    private function getLanguageService(): LanguageService
    {
        $lang = $GLOBALS['LANG'] ?? null;
        \assert($lang instanceof LanguageService);

        return $lang;
    }
}
