<?php

declare(strict_types=1);

namespace Netresearch\NrLandingpage\Service;

use Doctrine\DBAL\ParameterType;
use TYPO3\CMS\Core\Database\ConnectionPool;

/**
 * Detects whether a page was created by the Landing Page Wizard.
 */
readonly class LandingPageDetectionService
{
    public function __construct(
        private ConnectionPool $connectionPool,
    ) {}

    /**
     * Check if a page has a non-zero tx_nrlandingpage_template_uid,
     * meaning it was generated by the Landing Page Wizard.
     */
    public function isGeneratedLandingPage(int $pageUid): bool
    {
        if ($pageUid <= 0) {
            return false;
        }

        $queryBuilder = $this->connectionPool->getQueryBuilderForTable('pages');
        $templateUid = $queryBuilder
            ->select('tx_nrlandingpage_template_uid')
            ->from('pages')
            ->where(
                $queryBuilder->expr()->eq('uid', $queryBuilder->createNamedParameter($pageUid, ParameterType::INTEGER)),
            )
            ->executeQuery()
            ->fetchOne();

        return is_numeric($templateUid) && (int) $templateUid > 0;
    }
}
